### ISSUE TITLE
After a new user signs in, 304 error generated

### ISSUE THREAD

**Issue by deepbig** [deepbig/42Matcha#4]
My guessing is the error generated in pull/user.

Here is the log:
```
GET /api/tags?type=preference 304 137.446 ms - -
GET /api/tags?type=myself 304 140.900 ms - -
GET /api/blocks 304 138.228 ms - -
GET /api/notifications 304 137.980 ms - -
GET /api/users?userId=-1 304 138.724 ms - -
GET /api/likes?type=chat 304 288.157 ms - `-`
GET /api/overviews 304 290.077 ms - -
GET /api/likes?type=follow 304 422.576 ms - -
```

**Comment by deepbig** [comment]
More detail message after some modification:

```

GET /api/users?userId=-1 200 165.828 ms - 382
GET /api/logs 200 175.879 ms - 296
GET /api/tags?type=myself 304 172.577 ms - -
GET /api/tags?type=preference 304 339.543 ms - -
Session {
  cookie: {
    path: '/',
    _expires: 2020-02-13T22:55:15.292Z,
    originalMaxAge: 86400000,
    httpOnly: true
  },
  userId: 1
}
GET /api/blocks 304 162.058 ms - -
GET /api/overviews 304 345.490 ms - -
GET /api/notifications 304 174.310 ms - -
GET /api/likes?type=chat 304 348.520 ms - -
Error: No default engine was specified and no extension was provided.
    at new View (/Users/hryu/Desktop/Logitech/Proejct/42Matcha/server/node_modules/express/lib/view.js:61:11)
    at Function.render (/Users/hryu/Desktop/Logitech/Proejct/42Matcha/server/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/Users/hryu/Desktop/Logitech/Proejct/42Matcha/server/node_modules/express/lib/response.js:1008:7)
    at /Users/hryu/Desktop/Logitech/Proejct/42Matcha/server/app.js:238:7
    at Layer.handle_error (/Users/hryu/Desktop/Logitech/Proejct/42Matcha/server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/hryu/Desktop/Logitech/Proejct/42Matcha/server/node_modules/express/lib/router/index.js:315:13)
    at /Users/hryu/Desktop/Logitech/Proejct/42Matcha/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/hryu/Desktop/Logitech/Proejct/42Matcha/server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/hryu/Desktop/Logitech/Proejct/42Matcha/server/node_modules/express/lib/router/index.js:275:10)
    at /Users/hryu/Desktop/Logitech/Proejct/42Matcha/server/app.js:225:3
GET /api/undefinednull 404 5.548 ms - 1440
GET /api/users?userId=-1 304 163.689 ms - -
GET /api/likes?type=follow 304 512.904 ms - -
```
